name: Content Suggestion
description: Suggest new content, improvements, or clarifications
title: "[Suggestion]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting improvements to the Canon! Please provide details below.

  - type: dropdown
    id: suggestion-type
    attributes:
      label: Type of Suggestion
      description: What type of content suggestion is this?
      options:
        - New section or principle
        - Clarification of existing content
        - Additional examples or explanations
        - Structural improvement
        - New ritual or practice
        - Other
    validations:
      required: true

  - type: input
    id: affected-section
    attributes:
      label: Affected Section (if applicable)
      description: Which section would this change or relate to?
      placeholder: e.g., "sections/03-practices.md" or "New section"

  - type: textarea
    id: suggestion
    attributes:
      label: Detailed Suggestion
      description: Describe your suggestion in detail.
      placeholder: What would you like to see added, changed, or clarified?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why do you think this suggestion would improve the Canon?
      placeholder: Explain the reasoning behind your suggestion...
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content (optional)
      description: If you have specific wording or content in mind, share it here.
      placeholder: Draft text or specific changes you'd suggest...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that would be helpful.
      placeholder: References, related discussions, etc...